# Generated by Django 4.2.3 on 2023-08-21 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0004_order_status_book_back_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_status',
            old_name='name',
            new_name='order_status',
        ),
    ]
