# Generated by Django 4.2.3 on 2023-07-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_details_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
