# Generated by Django 4.2.3 on 2023-07-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_details_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
