# Generated by Django 4.2.3 on 2023-08-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_remove_order_order_status_cartitem_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(default='order placed'),
        ),
    ]
