# Generated by Django 4.2.3 on 2023-08-26 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0006_alter_order_status_order_status'),
        ('userapp', '0006_orderitem_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='order_status',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.ForeignKey(default='order placed', on_delete=django.db.models.deletion.CASCADE, to='admin_side.order_status'),
        ),
    ]
