# Generated by Django 4.2.3 on 2023-09-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
