# Generated by Django 4.2.3 on 2023-10-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_alter_other_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='other',
        ),
    ]
