# Generated by Django 4.2.3 on 2023-10-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0007_coupon'),
        ('userapp', '0015_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='order_item',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='admin_side.book'),
        ),
    ]
